import type { ThemeVariables } from "../types";
export type CollectionId =
  "minimal" | "editorial" | "ledger" | "authority" | "blueprint";
const sans = "var(--font-geist-sans), var(--resume-cjk-sans)";
const serif = "var(--font-fraunces), var(--resume-cjk-serif)";
const core: ThemeVariables = {
  collectionVersion: 2,
  fontFamily: sans,
  headingFontFamily: sans,
  baseFontSize: "10pt",
  lineHeight: 1.65,
  marginTop: "19mm",
  marginBottom: "18mm",
  marginLeft: "20mm",
  marginRight: "20mm",
  textColor: "#252b2a",
  secondaryColor: "#626c67",
  backgroundColor: "#ffffff",
};
export const collectionThemes: Record<CollectionId, ThemeVariables> = {
  minimal: {
    ...core,
    primaryColor: "#242a28",
    secondaryColor: "#626a65",
    headingFontFamily: serif,
    marginTop: "23mm",
    marginLeft: "23mm",
    marginRight: "23mm",
    lineHeight: 1.7,
  },
  editorial: {
    ...core,
    primaryColor: "#624b4e",
    secondaryColor: "#716b66",
    backgroundColor: "#fcfaf6",
    headingFontFamily: serif,
    marginTop: "19mm",
    marginLeft: "18mm",
    marginRight: "18mm",
    baseFontSize: "9.8pt",
    lineHeight: 1.65,
  },
  ledger: {
    ...core,
    primaryColor: "#ae4035",
    secondaryColor: "#60666a",
    textColor: "#22272a",
    marginTop: "17mm",
    marginLeft: "18mm",
    marginRight: "18mm",
    baseFontSize: "9.8pt",
    lineHeight: 1.6,
  },
  authority: {
    ...core,
    primaryColor: "#284c45",
    secondaryColor: "#68736b",
    textColor: "#29362f",
    backgroundColor: "#fdfcf9",
    headingFontFamily: serif,
    marginTop: "19mm",
    marginLeft: "22mm",
    marginRight: "22mm",
    lineHeight: 1.65,
  },
  blueprint: {
    ...core,
    primaryColor: "#263f57",
    secondaryColor: "#5b6f7e",
    textColor: "#293743",
    fontFamily: "var(--font-plex-sans), var(--resume-cjk-sans)",
    headingFontFamily: sans,
    marginTop: "16mm",
    marginBottom: "16mm",
    marginLeft: "16mm",
    marginRight: "16mm",
    baseFontSize: "9.8pt",
    lineHeight: 1.6,
  },
};
