import type { ThemeVariables } from "../types";

// Frozen pre-collection defaults distinguish saved defaults from user adjustments.
export const legacyDefaults: Record<string, ThemeVariables> = {
  minimal: {
    primaryColor: "#111111",
    secondaryColor: "#666666",
    backgroundColor: "#ffffff",
    textColor: "#111111",
    fontFamily:
      "var(--font-fraunces), 'Iowan Old Style', Georgia, var(--resume-cjk-serif)",
    headingFontFamily: "var(--font-fraunces), var(--resume-cjk-serif)",
    baseFontSize: "10.5pt",
    lineHeight: 1.65,
    marginTop: "22mm",
    marginBottom: "22mm",
    marginLeft: "26mm",
    marginRight: "26mm",
  },
  tech: {
    primaryColor: "#0a3a5c",
    secondaryColor: "#5a6b7d",
    backgroundColor: "#fbfaf6",
    textColor: "#1a2332",
    fontFamily: "var(--font-plex-sans), -apple-system, var(--resume-cjk-sans)",
    headingFontFamily: "var(--font-plex-sans), var(--resume-cjk-sans)",
    baseFontSize: "10.5pt",
    lineHeight: 1.55,
    marginTop: "16mm",
    marginBottom: "16mm",
    marginLeft: "18mm",
    marginRight: "18mm",
  },
  developer: {
    primaryColor: "#2d5a3d",
    secondaryColor: "#6a7570",
    backgroundColor: "#fbfaf7",
    textColor: "#18221c",
    fontFamily:
      "var(--font-inter-tight), -apple-system, var(--resume-cjk-sans)",
    headingFontFamily: "var(--font-inter-tight), var(--resume-cjk-sans)",
    baseFontSize: "10.5pt",
    lineHeight: 1.6,
    marginTop: "18mm",
    marginBottom: "18mm",
    marginLeft: "20mm",
    marginRight: "20mm",
  },
  grid: {
    primaryColor: "#000000",
    secondaryColor: "#dc2626",
    backgroundColor: "#ffffff",
    textColor: "#0a0a0a",
    fontFamily: "var(--font-geist-sans), -apple-system, var(--resume-cjk-sans)",
    headingFontFamily: "var(--font-geist-sans), var(--resume-cjk-sans)",
    baseFontSize: "10pt",
    lineHeight: 1.5,
    marginTop: "20mm",
    marginBottom: "20mm",
    marginLeft: "22mm",
    marginRight: "20mm",
  },
  editorial: {
    primaryColor: "#3a2415",
    secondaryColor: "#a87b3f",
    backgroundColor: "#faf6ed",
    textColor: "#2a1c10",
    fontFamily:
      "var(--font-fraunces), 'Iowan Old Style', Georgia, var(--resume-cjk-serif)",
    headingFontFamily: "var(--font-fraunces), var(--resume-cjk-serif)",
    baseFontSize: "10.5pt",
    lineHeight: 1.62,
    marginTop: "22mm",
    marginBottom: "22mm",
    marginLeft: "26mm",
    marginRight: "26mm",
  },
  executive: {
    primaryColor: "#173b35",
    secondaryColor: "#b68b2d",
    backgroundColor: "#fcfcfa",
    textColor: "#182421",
    fontFamily:
      "var(--font-inter-tight), -apple-system, var(--resume-cjk-sans)",
    headingFontFamily: "var(--font-fraunces), Georgia, var(--resume-cjk-serif)",
    baseFontSize: "10.3pt",
    lineHeight: 1.56,
    marginTop: "20mm",
    marginBottom: "18mm",
    marginLeft: "22mm",
    marginRight: "22mm",
  },
  compact: {
    primaryColor: "#111827",
    secondaryColor: "#2563eb",
    backgroundColor: "#ffffff",
    textColor: "#111827",
    fontFamily: "var(--font-geist-sans), -apple-system, var(--resume-cjk-sans)",
    headingFontFamily: "var(--font-geist-sans), var(--resume-cjk-sans)",
    baseFontSize: "9.6pt",
    lineHeight: 1.42,
    marginTop: "14mm",
    marginBottom: "14mm",
    marginLeft: "16mm",
    marginRight: "16mm",
  },
  ledger: {
    primaryColor: "#d42c24",
    secondaryColor: "#687078",
    backgroundColor: "#ffffff",
    textColor: "#111214",
    fontFamily: "var(--font-plex-sans), -apple-system, var(--resume-cjk-sans)",
    headingFontFamily:
      "var(--font-inter-tight), -apple-system, var(--resume-cjk-sans)",
    baseFontSize: "9.8pt",
    lineHeight: 1.48,
    marginTop: "14mm",
    marginBottom: "14mm",
    marginLeft: "14mm",
    marginRight: "14mm",
  },
  authority: {
    primaryColor: "#213b36",
    secondaryColor: "#a97828",
    backgroundColor: "#fbf8f1",
    textColor: "#202725",
    fontFamily:
      "var(--font-inter-tight), -apple-system, var(--resume-cjk-sans)",
    headingFontFamily: "var(--font-fraunces), Georgia, var(--resume-cjk-serif)",
    baseFontSize: "10.5pt",
    lineHeight: 1.55,
    marginTop: "15mm",
    marginBottom: "15mm",
    marginLeft: "16mm",
    marginRight: "16mm",
  },
  blueprint: {
    primaryColor: "#1452c2",
    secondaryColor: "#52647d",
    backgroundColor: "#ffffff",
    textColor: "#111a2d",
    fontFamily: "var(--font-plex-sans), -apple-system, var(--resume-cjk-sans)",
    headingFontFamily:
      "var(--font-inter-tight), -apple-system, var(--resume-cjk-sans)",
    baseFontSize: "9.4pt",
    lineHeight: 1.46,
    marginTop: "10mm",
    marginBottom: "10mm",
    marginLeft: "10mm",
    marginRight: "10mm",
  },
};
